### ISSUE TITLE
Feedback on the second submission

### ISSUE THREAD

**Issue by Anisha7** [noltron000/data-structures#3]
Good job on completing your second coding challenge. Here's some feedback to improve your code:
- [x] Optimizing your LinkedStack is required. The top of the stack should be the head of your linked list for O(1) operations.
- [x] Optimizing your LinkedQueue is required. The front of the queue should be at the head.
- [x] For sets, implementing is_subset is required for full credit.
- [x] Medium post should be at least 800 words.

**Comment by noltron000** [comment]
Thanks Anisha, looks like these are fixed now!
